dbt_xkcd:
  outputs:
    dev:
      dbname: airflow
      host: host.docker.internal
      pass: airflow
      port: 5432
      schema: xkcd
      threads: 1
      type: postgres
      user: airflow
  target: dev